### ISSUE TITLE
Initial Project Setup

### ISSUE THREAD

**Issue by KarnesTH** [KarnesTH/rustique-ui#1]
## Objective
Set up the basic project structure and development environment

## Project Structure
```mermaid
graph TD
    A[rustique-ui] --> B[core]
    A --> C[platform]
    A --> D[widgets]
    C --> E[x11]
    C --> F[windows]
    C --> G[macos]
    D --> H[basic]
    D --> I[containers]
    B --> J[event]
    B --> K[render]
```

## Data Flow
```mermaid
graph LR
    A[App] --> B[Window]
    B --> C[Event System]
    B --> D[Render System]
    C --> E[Widget Tree]
    D --> E
    E --> F[Layout Engine]
    F --> D
```

## Tasks
- [x] Create basic directory structure
- [x] Set up module organization
- [x] Configure build system
- [x] Add initial documentation
- [x] Set up example directory

## Acceptance Criteria
- Project builds successfully
- Directory structure follows platform-agnostic design
- Basic documentation is in place
- Example directory is ready for demos
